### ISSUE TITLE
Bug: Some Content-Security-Policy values breaking the functionality/design

### ISSUE THREAD

**Issue by sushidave** [trilbymedia/grav-plugin-custom-http-headers#2]
Thank you for this useful plugin.

Some Content-Security-Policy values break the functionality or design of the plugin page:

**Examples:**

default-src 'self'
and
default-src 'self' frame-ancestors 'none'
=> Effect: Custom Header records can't be added or removed anymore. The plus and minus buttons don't work.

default-src 'none'
=> Effect: shows an unstyled plugin page.

Grav v1.7.43
Plugin v1.0.1

**Comment by rhukster** [comment]
I think you just need to set: `enabled_in_admin: false` in the confuiguration if you want to use the admin

**Comment by sushidave** [comment]
Thanks @rhukster . It helped.

With `enabled_in_admin: true` the plugin details on the plugin list can't be expanded and the content of Pages don't load.
